### PR TITLE
For TSE Review

### PR DESCRIPTION
**Pull request by paulo-techie**
- Recreated newsweek.com homepage as per requirement
- Extensively used bootstrap to achieve most of the styling with a little css for a couple of media queries
- Used bootstrap tags and some CSS media queries to achieve smooth responsivness for different media sizes
- A lot of content is repeated to save time but the idea is to demonstrate mastery of the layout and style used in each section

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @paulo-techie. You have a nice project:+1:. You deserve :trophy: for your usage of bootstrap classes.**
But you need to fix the following for this project to be approved:

1. On large screens, reduce the left and right margin of the container housing the entire page. Compare yours with the original.

2. On small and medium screen sizes, the header and footer do not look proper.
Check the size of the logo and the height of the navbar  and especially for the small screen check the alignment of elements on the nav bar.

image

3. On small screens, adjust the left and right margin for the top story and featured stories sections.

4. Image to text width ratio in the section below (just before the SUBSCRIBE ) on small screens is to be 50/50. 
image

5. Elements in the footer on small screens should be left aligned properly.
footer
 

_**Kindly take care of the above and submit another code review request.**_

**Cheers:stars:**

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @paulo-techie      
#### Great Job so far, but there is one more thing required. 
### General
- [ ] It seems your Linters isn't working(Am not seeing All checks have passed), Please fix that.

### Make changes and submit another code review request.
*Happy coding*

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @paulo-techie  ,  You have done a great job with this project. :clap:

**Pull request merged**
